<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mime-info [
  <!ELEMENT mime-info (mime-type)+>
  <!ATTLIST mime-info xmlns CDATA #FIXED "http://www.freedesktop.org/standards/shared-mime-info">

  <!ELEMENT mime-type (comment+, (acronym,expanded-acronym)? , (icon? | generic-icon? | glob | magic | treemagic | root-XML | alias | sub-class-of)*)>
  <!ATTLIST mime-type type CDATA #REQUIRED>

  <!-- a comment describing a document with the respective MIME type. Example: "WMV video" -->
  <!ELEMENT comment (#PCDATA)>
  <!ATTLIST comment xml:lang CDATA #IMPLIED>

  <!-- a comment describing the respective unexpanded MIME type acronym. Example: "WMV" -->
  <!ELEMENT acronym (#PCDATA)>
  <!ATTLIST acronym xml:lang CDATA #IMPLIED>

  <!-- a comment describing the respective expanded MIME type acronym. Example: "Windows Media Video" -->
  <!ELEMENT expanded-acronym (#PCDATA)>
  <!ATTLIST expanded-acronym xml:lang CDATA #IMPLIED>

  <!ELEMENT icon EMPTY>
  <!ATTLIST icon name CDATA #REQUIRED>

  <!-- a generic icon name as per the Icon Naming Specification, only required if computing
  it from the mime-type would not work, See "generic-icon" in the Shared Mime Specification -->
  <!ELEMENT generic-icon EMPTY>
  <!ATTLIST generic-icon name (application-x-executable|audio-x-generic|folder|font-x-generic|image-x-generic|package-x-generic|text-html|text-x-generic|text-x-generic-template|text-x-script|video-x-generic|x-office-address-book|x-office-calendar|x-office-document|x-office-presentation|x-office-spreadsheet) #REQUIRED>

  <!ELEMENT glob EMPTY>
  <!ATTLIST glob pattern CDATA #REQUIRED>
  <!ATTLIST glob weight CDATA "50">
  <!ATTLIST glob case-sensitive CDATA #IMPLIED>

  <!ELEMENT magic (match)+>
  <!ATTLIST magic priority CDATA "50">

  <!ELEMENT match (match)*>
  <!ATTLIST match offset CDATA #REQUIRED>
  <!ATTLIST match type (string|big16|big32|little16|little32|host16|host32|byte) #REQUIRED>
  <!ATTLIST match value CDATA #REQUIRED>
  <!ATTLIST match mask CDATA #IMPLIED>

  <!ELEMENT treemagic (treematch)+>
  <!ATTLIST treemagic priority CDATA "50">

  <!ELEMENT treematch (treematch)*>
  <!ATTLIST treematch path CDATA #REQUIRED>
  <!ATTLIST treematch type (file|directory|link) #IMPLIED>
  <!ATTLIST treematch match-case (true|false) #IMPLIED>
  <!ATTLIST treematch executable (true|false) #IMPLIED>
  <!ATTLIST treematch non-empty (true|false) #IMPLIED>
  <!ATTLIST treematch mimetype CDATA #IMPLIED>

  <!ELEMENT root-XML EMPTY>
  <!ATTLIST root-XML namespaceURI CDATA #REQUIRED>
  <!ATTLIST root-XML localName CDATA #REQUIRED>

  <!ELEMENT alias EMPTY>
  <!ATTLIST alias type CDATA #REQUIRED>

  <!ELEMENT sub-class-of EMPTY>
  <!ATTLIST sub-class-of type CDATA #REQUIRED>
]>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="application/andrew-inset">
    <comment>ATK inset</comment>
    <comment xml:lang="ar">شكل ATK</comment>
    <comment xml:lang="be@latin">Ustaŭka ATK</comment>
    <comment xml:lang="bg">Сбор — ATK</comment>
    <comment xml:lang="ca">inset ATK</comment>
    <comment xml:lang="cs">vložka ATK</comment>
    <comment xml:lang="da">ATK-indsættelse</comment>
    <comment xml:lang="de">ATK-Inset</comment>
    <comment xml:lang="el">Ένθετο ATK</comment>
    <comment xml:lang="en_GB">ATK inset</comment>
    <comment xml:lang="es">inserción ATK</comment>
    <comment xml:lang="eu">ATK sartzapena</comment>
    <comment xml:lang="fi">ATK-osio</comment>
    <comment xml:lang="fo">ATK innskot</comment>
    <comment xml:lang="fr">encart ATK</comment>
    <comment xml:lang="ga">intlis ATK</comment>
    <comment xml:lang="gl">conxunto ATK</comment>
    <comment xml:lang="he">תוספת ATK</comment>
    <comment xml:lang="hu">ATK betét</comment>
    <comment xml:lang="ia">Folio intercalari ATK</comment>
    <comment xml:lang="id">Inset ATK</comment>
    <comment xml:lang="it">Inset ATK</comment>
    <comment xml:lang="ja">ATK インセット</comment>
    <comment xml:lang="kk">ATK беті</comment>
    <comment xml:lang="ko">ATK inset</comment>
    <comment xml:lang="lt">ATK inset</comment>
    <comment xml:lang="lv">ATK ielaidums</comment>
    <comment xml:lang="nb">ATK-innsats</comment>
    <comment xml:lang="nl">ATK-invoegsel</comment>
    <comment xml:lang="nn">ATK-innskot</comment>
    <comment xml:lang="pl">Wstawka ATK</comment>
    <comment xml:lang="pt_BR">Conjunto de entrada do ATK</comment>
    <comment xml:lang="ro">Inset ATK</comment>
    <comment xml:lang="ru">вкладка ATK</comment>
    <comment xml:lang="sk">Vložka ATK</comment>
    <comment xml:lang="sl">Vložka ATK</comment>
    <comment xml:lang="sq">Inset ATK</comment>
    <comment xml:lang="sr">АТК уметак</comment>
    <comment xml:lang="sv">ATK-inlägg</comment>
    <comment xml:lang="tr">ATK iç metni</comment>
    <comment xml:lang="uk">вкладка ATK</comment>
    <comment xml:lang="vi">Bộ dát ATK</comment>
    <comment xml:lang="zh_CN">ATK 嵌入对象</comment>
    <comment xml:lang="zh_TW">ATK 內嵌</comment>
    <acronym>ATK</acronym>
    <expanded-acronym>Andrew Toolkit</expanded-acronym>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.ez"/>
  </mime-type>
  <mime-type type="application/epub+zip">
    <comment>electronic book document</comment>
    <comment xml:lang="ar">مستند كتاب إلكتروني</comment>
    <comment xml:lang="be@latin">elektronnaja kniha</comment>
    <comment xml:lang="bg">Документ — електронна книга</comment>
    <comment xml:lang="ca">document de llibre electrònic</comment>
    <comment xml:lang="cs">dokument elektronické knihy</comment>
    <comment xml:lang="da">elektronisk bogdokument</comment>
    <comment xml:lang="de">Elektronisches Buch</comment>
    <comment xml:lang="el">Έγγραφο ηλεκτρονικού βιβλίου</comment>
    <comment xml:lang="en_GB">electronic book document</comment>
    <comment xml:lang="es">documento de libro electrónico</comment>
    <comment xml:lang="eu">liburu elektronikoaren dokumentua</comment>
    <comment xml:lang="fi">elektroninen kirja</comment>
    <comment xml:lang="fo">elektroniskbóka skjal</comment>
    <comment xml:lang="fr">document livre électronique</comment>
    <comment xml:lang="ga">leabhar leictreonach</comment>
    <comment xml:lang="gl">documento de libro electrónico</comment>
    <comment xml:lang="he">מסמך מסוג ספר אלקטרוני</comment>
    <comment xml:lang="hr">dokument elektroničke knjige</comment>
    <comment xml:lang="hu">elektronikus könyvdokumentum</comment>
    <comment xml:lang="ia">Documento de libro electronic</comment>
    <comment xml:lang="id">dokumen buku elektronik</comment>
    <comment xml:lang="it">Documento libro elettronico</comment>
    <comment xml:lang="ja">電子ブックドキュメント</comment>
    <comment xml:lang="kk">электронды кітабы</comment>
    <comment xml:lang="ko">전자책 문서</comment>
    <comment xml:lang="lt">elektroninės knygos dokumentas</comment>
    <comment xml:lang="lv">elektroniskās grāmatas dokuments</comment>
    <comment xml:lang="nl">elektronisch boek</comment>
    <comment xml:lang="nn">elektronisk bok-dokument</comment>
    <comment xml:lang="pl">Dokument książki elektronicznej</comment>
    <comment xml:lang="pt_BR">Documento de livro eletrônico</comment>
    <comment xml:lang="ro">document carte electronică</comment>
    <comment xml:lang="ru">электронная книга</comment>
    <comment xml:lang="sk">Dokument elektronickej knihy</comment>
    <comment xml:lang="sl">dokument elektronske knjige</comment>
    <comment xml:lang="sq">Dokument libri elektronik</comment>
    <comment xml:lang="sr">документ електронске књиге</comment>
    <comment xml:lang="sv">elektroniskt bokdokument</comment>
    <comment xml:lang="tr">elektronik kitap belgesi</comment>
    <comment xml:lang="uk">документ електронної книги</comment>
    <comment xml:lang="vi">tài liệu cuốn sách điện tử</comment>
    <comment xml:lang="zh_CN">电子书文档</comment>
    <comment xml:lang="zh_TW">電子書文件</comment>
    <sub-class-of type="application/zip"/>
    <generic-icon name="x-office-document"/>
    <magic priority="50">
      <match value="PK\003\004" type="string" offset="0">
        <match value="mimetype" type="string" offset="30">
          <match value="application/epub+zip" type="string" offset="38"/>
          <match value="application/epub+zip" type="string" offset="43"/>
        </match>
      </match>
    </magic>
    <glob pattern="*.epub"/>
  </mime-type>
  <mime-type type="application/illustrator">
    <comment>Adobe Illustrator document</comment>
    <comment xml:lang="ar">مستند أدوبي المصور</comment>
    <comment xml:lang="be@latin">Dakument Adobe Illustrator</comment>
    <comment xml:lang="bg">Документ — Adobe Illustrator</comment>
    <comment xml:lang="ca">document d'Adobe Illustrator</comment>
    <comment xml:lang="cs">dokument Adobe Illustrator</comment>
    <comment xml:lang="da">Adobe Illustrator-dokument</comment>
    <comment xml:lang="de">Adobe-Illustrator-Dokument</comment>
    <comment xml:lang="el">Έγγραφο Adobe Illustrator</comment>
    <comment xml:lang="en_GB">Adobe Illustrator document</comment>
    <comment xml:lang="eo">dokumento de Adobe Illustrator</comment>
    <comment xml:lang="es">documento de Adobe Illustrator</comment>
    <comment xml:lang="eu">Adobe Illustrator dokumentua</comment>
    <comment xml:lang="fi">Adobe Illustrator -asiakirja</comment>
    <comment xml:lang="fo">Adobe Illustrator skjal</comment>
    <comment xml:lang="fr">document Adobe Illustrator</comment>
    <comment xml:lang="ga">cáipéis Adobe Illustrator</comment>
    <comment xml:lang="gl">documento de Adobe Ilustrator</comment>
    <comment xml:lang="he">מסמך Adobe Ill</comment>
    <comment xml:lang="hr">Adobe Illustrator dokument</comment>
    <comment xml:lang="hu">Adobe Illustrator-dokumentum</comment>
    <comment xml:lang="ia">Documento Adobe Illustrator</comment>
    <comment xml:lang="id">Dokumen Adobe Illustrator</comment>
    <comment xml:lang="it">Documento Adobe Illustrator</comment>
    <comment xml:lang="ja">Adobe Illustrator ドキュメント</comment>
    <comment xml:lang="ka">Adobe Illustrator-ის დოკუმენტი</comment>
    <comment xml:lang="kk">Adobe Illustrator құжаты</comment>
    <comment xml:lang="ko">Adobe Illustrator 문서</comment>
    <comment xml:lang="lt">Adobe Illustrator dokumentas</comment>
    <comment xml:lang="lv">Adobe Illustrator dokuments</comment>
    <comment xml:lang="ms">Dokumen Adobe Illustrator</comment>
    <comment xml:lang="nb">Adobe Illustrator-dokument</comment>
    <comment xml:lang="nl">Adobe Illustrator-document</comment>
    <comment xml:lang="nn">Adobe Illustrator-dokument</comment>
    <comment xml:lang="pl">Dokument Adobe Illustrator</comment>
    <comment xml:lang="pt">documento Adobe Illustrator</comment>
    <comment xml:lang="pt_BR">Documento do Adobe Illustrator</comment>
    <comment xml:lang="ro">Document Adobe Illustrator</comment>
    <comment xml:lang="ru">документ Adobe Illustrator</comment>
    <comment xml:lang="sk">Dokument Adobe Illustrator</comment>
    <comment xml:lang="sl">Dokument Adobe Illustrator</comment>
    <comment xml:lang="sq">Dokument Adobe Illustrator</comment>
    <comment xml:lang="sr">документ Адобе Илустратора</comment>
    <comment xml:lang="sv">Adobe Illustrator-dokument</comment>
    <comment xml:lang="tr">Adobe Illustrator belgesi</comment>
    <comment xml:lang="uk">документ Adobe Illustrator</comment>
    <comment xml:lang="vi">Tài liệu Adobe Illustrator</comment>
    <comment xml:lang="zh_CN">Adobe Illustrator 文档</comment>
    <comment xml:lang="zh_TW">Adobe Illustrator 文件</comment>
    <generic-icon name="image-x-generic"/>
    <glob pattern="*.ai"/>
  </mime-type>
  <mime-type type="application/mac-binhex40">
    <comment>Macintosh BinHex-encoded file</comment>
    <comment xml:lang="ar">ملف Macintosh BinHex مشفر</comment>
    <comment xml:lang="az">Macintosh BinHex-kodlanmış fayl</comment>
    <comment xml:lang="be@latin">Fajł Macintosh, BinHex-zakadavany</comment>
    <comment xml:lang="bg">Файл — кодиран във формат BinHex за Macintosh</comment>
    <comment xml:lang="ca">fitxer codificat BinHex de Macintosh</comment>
    <comment xml:lang="cs">soubor kódovaný pomocí Macintosh BinHex</comment>
    <comment xml:lang="cy">Ffeil BinHex-amgodwyd Macintosh</comment>
    <comment xml:lang="da">Macintosh BinHex-kodet fil</comment>
    <comment xml:lang="de">Macintosh-Datei (BinHex-kodiert)</comment>
    <comment xml:lang="el">Αρχείο Macintosh κωδικοποίησης BinHex</comment>
    <comment xml:lang="en_GB">Macintosh BinHex-encoded file</comment>
    <comment xml:lang="eo">dosiero kodigita laŭ Macintosh BinHex</comment>
    <comment xml:lang="es">archivo Macintosh codificado con BinHex</comment>
    <comment xml:lang="eu">Macintosh BinHex-ekin kodetutako fitxategia</comment>
    <comment xml:lang="fi">Macintosh BinHex -koodattu tiedosto</comment>
    <comment xml:lang="fo">Macintosh BinHex-bronglað fíla</comment>
    <comment xml:lang="fr">fichier codé Macintosh BinHex</comment>
    <comment xml:lang="ga">comhad ionchódaithe le Macintosh BinHex</comment>
    <comment xml:lang="gl">ficheiro de Macintosh codificado con BinHex</comment>
    <comment xml:lang="he">קובץ מסוג Macintosh BinHex-encoded</comment>
    <comment xml:lang="hr">Macintosh BinHex-kodirana datoteka</comment>
    <comment xml:lang="hu">Macintosh BinHex kódolású fájl</comment>
    <comment xml:lang="ia">File codificate in BinHex de Macintosh</comment>
    <comment xml:lang="id">Berkas tersandi Macintosh BinHex</comment>
    <comment xml:lang="it">File Macintosh codificato BinHex</comment>
    <comment xml:lang="ja">Macintosh BinHex エンコードファイル</comment>
    <comment xml:lang="kk">Macintosh BinHex кодталған файлы</comment>
    <comment xml:lang="ko">매킨토시 BinHex 인코딩된 압축 파일</comment>
    <comment xml:lang="lt">Macintosh BinHex-encoded failas</comment>
    <comment xml:lang="lv">Macintosh BinHex-kodēts datne</comment>
    <comment xml:lang="ms">Fail terenkod-BinHex Macintosh</comment>
    <comment xml:lang="nb">Macintosh BinHe-kodet arkiv</comment>
    <comment xml:lang="nl">Macintosh BinHex-gecodeerd bestand</comment>
    <comment xml:lang="nn">Macintosh BinHex-koda fil</comment>
    <comment xml:lang="pl">Zakodowany w BinHex plik Macintosh</comment>
    <comment xml:lang="pt">ficheiro codificado em BinHex de Macintosh</comment>
    <comment xml:lang="pt_BR">Arquivo do Macintosh codificado com BinHex</comment>
    <comment xml:lang="ro">Fișier codat Macintosh BinHex</comment>
    <comment xml:lang="ru">файл (закодированный Macintosh BinHex)</comment>
    <comment xml:lang="sk">Súbor kódovaný pomocou Macintosh BinHex</comment>
    <comment xml:lang="sl">Kodirana datoteka Macintosh (BinHex)</comment>
    <comment xml:lang="sq">File Macintosh i kodifikuar BinHex</comment>
    <comment xml:lang="sr">Мекинтошова БинХекс-кодирана датотека</comment>
    <comment xml:lang="sv">Macintosh BinHex-kodad fil</comment>
    <comment xml:lang="tr">Macintosh BinHex-şifreli dosya</comment>
    <comment xml:lang="uk">файл закодований Macintosh BinHex</comment>
    <comment xml:lang="vi">Tập tin đã mã hoá BinHex của Macintosh</comment>
    <comment xml:lang="zh_CN">Macintosh BinHex 编码的文件</comment>
    <comment xml:lang="zh_TW">Macintosh BinHex 編碼檔</comment>
    <generic-icon name="package-x-generic"/>
    <magic priority="50">
      <match value="must be converted with BinHex" type="string" offset="11"/>
    </magic>
  </mime-type>
  <mime-type type="application/mathematica">
    <comment>Mathematica Notebook</comment>
    <comment xml:lang="ar">مذكرة رياضيات</comment>
    <comment xml:lang="be@latin">Natatnik Mathematica</comment>
    <comment xml:lang="bg">Тетрадка — Mathematica</comment>
    <comment xml:lang="ca">llibreta de notes de Mathematica</comment>
    <comment xml:lang="cs">sešit Mathematica</comment>
    <comment xml:lang="da">Mathematica Notebook</comment>
    <comment xml:lang="de">Mathematica-Dokument</comment>
    <comment xml:lang="el">Σημειωματάριο Mathematica</comment>
    <comment xml:lang="en_GB">Mathematica Notebook</comment>
    <comment xml:lang="es">libreta de Mathematica</comment>
    <comment xml:lang="eu">Mathematica Notebook</comment>
    <comment xml:lang="fi">Mathematica-muistilehtiö</comment>
    <comment xml:lang="fo">Mathematica skriviblokkur</comment>
    <comment xml:lang="fr">carnet de notes Mathematica</comment>
    <comment xml:lang="ga">leabhar nótaí Mathematica</comment>
    <comment xml:lang="gl">notebook de Mathematica</comment>
    <comment xml:lang="he">מחברת מתמטיקה</comment>
    <comment xml:lang="hu">Mathematica notesz</comment>
    <comment xml:lang="ia">Carnet de notas Mathematica</comment>
    <comment xml:lang="id">Mathematica Notebook</comment>
    <comment xml:lang="it">Notebook Mathematica</comment>
    <comment xml:lang="ja">Mathematica ノートブック</comment>
    <comment xml:lang="kk">Mathematica Notebook</comment>
    <comment xml:lang="ko">Mathematica 노트북</comment>
    <comment xml:lang="lt">Mathematica užrašinė</comment>
    <comment xml:lang="lv">Mathematica bloknots</comment>
    <comment xml:lang="nb">Mathematica notisblokk</comment>
    <comment xml:lang="nl">Mathematica-notitieboek</comment>
    <comment xml:lang="nn">Mathematica-notatbok</comment>
    <comment xml:lang="pl">Notatnik Mathematica</comment>
    <comment xml:lang="pt_BR">Caderno do Mathematica</comment>
    <comment xml:lang="ro">Carnețel Mathematica</comment>
    <comment xml:lang="ru">Mathematica Notebook</comment>
    <comment xml:lang="sk">Zošit Mathematica</comment>
    <comment xml:lang="sl">Datoteka dokumenta Mathematica</comment>
    <comment xml:lang="sq">Notebook matematike</comment>
    <comment xml:lang="sr">бележница Математике</comment>
    <comment xml:lang="sv">Mathematica Notebook-dokument</comment>
    <comment xml:lang="tr">Mathematica Defteri</comment>
    <comment xml:lang="uk">математичний записник</comment>
    <comment xml:lang="vi">Cuốn vở Mathematica</comment>
    <comment xml:lang="zh_CN">Mathematica 记事</comment>
    <comment xml:lang="zh_TW">Mathematica Notebook</comment>
    <sub-class-of type="text/plain"/>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.nb"/>
    <magic priority="50">
      <match value="(************** Content-type: application/mathematica" type="string" offset="0"/>
      <match value="This notebook can be used on any computer system with Mathematica" type="string" offset="100:256"/>
      <match value="This is a Mathematica Notebook file.  It contains ASCII text" type="string" offset="10:256"/>
    </magic>
    <alias type="application/x-mathematica"/>
  </mime-type>
  <mime-type type="application/mathml+xml">
    <comment>MathML document</comment>
    <comment xml:lang="ar">مستند MathML</comment>
    <comment xml:lang="az">MathML sənədi</comment>
    <comment xml:lang="be@latin">Dakument MathML</comment>
    <comment xml:lang="bg">Документ — MathML</comment>
    <comment xml:lang="ca">document de MathML</comment>
    <comment xml:lang="cs">dokument MathML</comment>
    <comment xml:lang="cy">Dogfen MathML</comment>
    <comment xml:lang="da">MathML-dokument</comment>
    <comment xml:lang="de">MathML-Dokument</comment>
    <comment xml:lang="el">Έγγραφο MathML</comment>
    <comment xml:lang="en_GB">MathML document</comment>
    <comment xml:lang="eo">MathML-dokumento</comment>
    <comment xml:lang="es">documento MathML</comment>
    <comment xml:lang="eu">MathML dokumentua</comment>
    <comment xml:lang="fi">MathML-asiakirja</comment>
    <comment xml:lang="fo">MathML skjal</comment>
    <comment xml:lang="fr">document MathML</comment>
    <comment xml:lang="ga">cáipéis MathML</comment>
    <comment xml:lang="gl">documento de MathML</comment>
    <comment xml:lang="he">מסמך MathML</comment>
    <comment xml:lang="hr">MathML dokument</comment>
    <comment xml:lang="hu">MathML-dokumentum</comment>
    <comment xml:lang="ia">Documento MathML</comment>
    <comment xml:lang="id">Dokumen MathML</comment>
    <comment xml:lang="it">Documento MathML</comment>
    <comment xml:lang="ja">MathML ドキュメント</comment>
    <comment xml:lang="ka">MathML-ის დოკუმენტი</comment>
    <comment xml:lang="kk">MathML құжаты</comment>
    <comment xml:lang="ko">MathML 문서</comment>
    <comment xml:lang="lt">MathML dokumentas</comment>
    <comment xml:lang="lv">MathML dokuments</comment>
    <comment xml:lang="ms">Dokumen MathML</comment>
    <comment xml:lang="nb">MathML-dokument</comment>
    <comment xml:lang="nl">MathML-document</comment>
    <comment xml:lang="nn">MathML-dokument</comment>
    <comment xml:lang="pl">Dokument MathML</comment>
    <comment xml:lang="pt">documento MathML</comment>
    <comment xml:lang="pt_BR">Documento do MathML</comment>
    <comment xml:lang="ro">Document MathML</comment>
    <comment xml:lang="ru">документ MathML</comment>
    <comment xml:lang="sk">Dokument MathML</comment>
    <comment xml:lang="sl">Dokument MathML</comment>
    <comment xml:lang="sq">Dokument MathML</comment>
    <comment xml:lang="sr">МатМЛ документ</comment>
    <comment xml:lang="sv">MathML-dokument</comment>
    <comment xml:lang="tr">MathML belgesi</comment>
    <comment xml:lang="uk">документ MathML</comment>
    <comment xml:lang="vi">Tài liệu MathML</comment>
    <comment xml:lang="zh_CN">MathML 文档</comment>
    <comment xml:lang="zh_TW">MathML 文件</comment>
    <acronym>MathML</acronym>
    <expanded-acronym>Mathematical Markup Language</expanded-acronym>
    <alias type="text/mathml"/>
    <sub-class-of type="application/xml"/>
    <glob pattern="*.mml"/>
    <root-XML namespaceURI="http://www.w3.org/1998/Math/MathML" localName="math"/>
  </mime-type>
  <mime-type type="application/mbox">
    <comment>mailbox file</comment>
    <comment xml:lang="ar">ملف صندوق البريد</comment>
    <comment xml:lang="be@latin">fajł paštovaj skryni</comment>
    <comment xml:lang="bg">Файл — Mailbox</comment>
    <comment xml:lang="ca">fitxer mailbox</comment>
    <comment xml:lang="cs">soubor mailbox</comment>
    <comment xml:lang="da">postkassefil</comment>
    <comment xml:lang="de">Mailbox-Datei</comment>
    <comment xml:lang="el">Αρχείο mailbox</comment>
    <comment xml:lang="en_GB">mailbox file</comment>
    <comment xml:lang="es">archivo de buzón de correo</comment>
    <comment xml:lang="eu">mailbox fitxategia</comment>
    <comment xml:lang="fi">mailbox-tiedosto</comment>
    <comment xml:lang="fo">postkassafíla</comment>
    <comment xml:lang="fr">fichier boîte aux lettres</comment>
    <comment xml:lang="ga">comhad bhosca poist</comment>
    <comment xml:lang="gl">ficheiro de caixa de correo</comment>
    <comment xml:lang="he">קובץ תיבת-דואר</comment>
    <comment xml:lang="hr">datoteka poštanskog sandučića</comment>
    <comment xml:lang="hu">mailbox fájl</comment>
    <comment xml:lang="ia">File de cassa postal</comment>
    <comment xml:lang="id">berkas kotak surat</comment>
    <comment xml:lang="it">File mailbox</comment>
    <comment xml:lang="ja">メールボックスファイル</comment>
    <comment xml:lang="kk">пошта жәшігінің файлы</comment>
    <comment xml:lang="ko">메일함 파일</comment>
    <comment xml:lang="lt">pašto dėžutės failas</comment>
    <comment xml:lang="lv">pastkastītes datne</comment>
    <comment xml:lang="nb">postboksfil</comment>
    <comment xml:lang="nl">mailbox-bestand</comment>
    <comment xml:lang="nn">mailbox-fil</comment>
    <comment xml:lang="pl">Plik poczty (Mailbox)</comment>
    <comment xml:lang="pt_BR">Arquivo de caixa de correio</comment>
    <comment xml:lang="ro">fișier căsuță poștală</comment>
    <comment xml:lang="ru">файл почтового ящика</comment>
    <comment xml:lang="sk">Súbor mailbox</comment>
    <comment xml:lang="sl">datoteka poštnega predala</comment>
    <comment xml:lang="sq">File mailbox</comment>
    <comment xml:lang="sr">датотека поштанског сандучета</comment>
    <comment xml:lang="sv">brevlådefil</comment>
    <comment xml:lang="tr">posta kutusu dosyası</comment>
    <comment xml:lang="uk">файл поштової скриньки</comment>
    <comment xml:lang="vi">tập tin hộp thư</comment>
    <comment xml:lang="zh_CN">mailbox 文件</comment>
    <comment xml:lang="zh_TW">郵箱檔</comment>
    <generic-icon name="text-x-generic"/>
    <sub-class-of type="text/plain"/>
    <magic priority="20">
      <match value="From " type="string" offset="0"/>
    </magic>
    <glob pattern="*.mbox"/>
  </mime-type>
  <mime-type type="application/metalink+xml">
    <comment>Metalink file</comment>
    <comment xml:lang="ar">ملف ميتالنك</comment>
    <comment xml:lang="bg">Изтегляне — Metalink</comment>
    <comment xml:lang="ca">fitxer Metalink</comment>
    <comment xml:lang="cs">soubor metalink</comment>
    <comment xml:lang="da">Metahenvisningsfil</comment>
    <comment xml:lang="de">Metalink-Datei</comment>
    <comment xml:lang="el">Αρχείο Metalink</comment>
    <comment xml:lang="en_GB">Metalink file</comment>
    <comment xml:lang="eo">Metalink-dosiero</comment>
    <comment xml:lang="es">archivo de Metalink</comment>
    <comment xml:lang="eu">Metaestekaren fitxategia</comment>
    <comment xml:lang="fi">Metalink-tiedosto</comment>
    <comment xml:lang="fo">Metalink fíla</comment>
    <comment xml:lang="fr">fichier metalink</comment>
    <comment xml:lang="ga">comhad Metalink</comment>
    <comment xml:lang="gl">ficheiro Metalink</comment>
    <comment xml:lang="he">קובץ Metalink</comment>
    <comment xml:lang="hu">Metalink fájl</comment>
    <comment xml:lang="ia">File Metalink</comment>
    <comment xml:lang="id">Berkas Metalink</comment>
    <comment xml:lang="it">File Metalink</comment>
    <comment xml:lang="ja">Metalink ファイル</comment>
    <comment xml:lang="kk">Metalink файлы</comment>
    <comment xml:lang="ko">Metalink 파일</comment>
    <comment xml:lang="lt">Metalink failas</comment>
    <comment xml:lang="lv">Metalink datne</comment>
    <comment xml:lang="nl">Metalink bestand</comment>
    <comment xml:lang="pl">Plik Metalink</comment>
    <comment xml:lang="pt_BR">Arquivo Metalink</comment>
    <comment xml:lang="ro">Fișier Metalink</comment>
    <comment xml:lang="ru">файл Metalink</comment>
    <comment xml:lang="sk">Súbor Metalink</comment>
    <comment xml:lang="sl">Datoteka povezave Metalink</comment>
    <comment xml:lang="sr">датотека метавезе</comment>
    <comment xml:lang="sv">Metalink-fil</comment>
    <comment xml:lang="tr">Metalink dosyası</comment>
    <comment xml:lang="uk">файл метапосилання</comment>
    <comment xml:lang="zh_CN">元链接文件</comment>
    <comment xml:lang="zh_TW">Metalink 檔案</comment>
    <sub-class-of type="application/xml"/>
    <magic priority="50">
      <match value="&lt;metalink version=&quot;3.0&quot;" type="string" offset="0:256"/>
    </magic>
    <glob pattern="*.metalink"/>
    <root-XML namespaceURI="http://www.metalinker.org/" localName="metalink"/>
  </mime-type>
  <mime-type type="application/metalink4+xml">
    <comment>Metalink file</comment>
    <comment xml:lang="ar">ملف ميتالنك</comment>
    <comment xml:lang="bg">Изтегляне — Metalink</comment>
    <comment xml:lang="ca">fitxer Metalink</comment>
    <comment xml:lang="cs">soubor metalink</comment>
    <comment xml:lang="da">Metahenvisningsfil</comment>
    <comment xml:lang="de">Metalink-Datei</comment>
    <comment xml:lang="el">Αρχείο Metalink</comment>
    <comment xml:lang="en_GB">Metalink file</comment>
    <comment xml:lang="eo">Metalink-dosiero</comment>
    <comment xml:lang="es">archivo de Metalink</comment>
    <comment xml:lang="eu">Metaestekaren fitxategia</comment>
    <comment xml:lang="fi">Metalink-tiedosto</comment>
    <comment xml:lang="fo">Metalink fíla</comment>
    <comment xml:lang="fr">fichier metalink</comment>
    <comment xml:lang="ga">comhad Metalink</comment>
    <comment xml:lang="gl">ficheiro Metalink</comment>
    <comment xml:lang="he">קובץ Metalink</comment>
    <comment xml:lang="hu">Metalink fájl</comment>
    <comment xml:lang="ia">File Metalink</comment>
    <comment xml:lang="id">Berkas Metalink</comment>
    <comment xml:lang="it">File Metalink</comment>
    <comment xml:lang="ja">Metalink ファイル</comment>
    <comment xml:lang="kk">Metalink файлы</comment>
    <comment xml:lang="ko">Metalink 파일</comment>
    <comment xml:lang="lt">Metalink failas</comment>
    <comment xml:lang="lv">Metalink datne</comment>
    <comment xml:lang="nl">Metalink bestand</comment>
    <comment xml:lang="pl">Plik Metalink</comment>
    <comment xml:lang="pt_BR">Arquivo Metalink</comment>
    <comment xml:lang="ro">Fișier Metalink</comment>
    <comment xml:lang="ru">файл Metalink</comment>
    <comment xml:lang="sk">Súbor Metalink</comment>
    <comment xml:lang="sl">Datoteka povezave Metalink</comment>
    <comment xml:lang="sr">датотека метавезе</comment>
    <comment xml:lang="sv">Metalink-fil</comment>
    <comment xml:lang="tr">Metalink dosyası</comment>
    <comment xml:lang="uk">файл метапосилання</comment>
    <comment xml:lang="zh_CN">元链接文件</comment>
    <comment xml:lang="zh_TW">Metalink 檔案</comment>
    <sub-class-of type="application/xml"/>
    <magic priority="50">
      <match value="&lt;metalink xmlns=&quot;urn" type="string" offset="0:256"/>
    </magic>
    <glob pattern="*.meta4"/>
    <root-XML namespaceURI="urn:ietf:params:xml:ns:metalink" localName="metalink"/>
  </mime-type>
  <mime-type type="application/octet-stream">
    <comment>unknown</comment>
    <comment xml:lang="ar">مجهول</comment>
    <comment xml:lang="be@latin">nieviadomy</comment>
    <comment xml:lang="bg">Неизвестен тип</comment>
    <comment xml:lang="ca">desconegut</comment>
    <comment xml:lang="cs">neznámý</comment>
    <comment xml:lang="da">ukendt</comment>
    <comment xml:lang="de">Unbekannt</comment>
    <comment xml:lang="el">Άγνωστο</comment>
    <comment xml:lang="en_GB">unknown</comment>
    <comment xml:lang="eo">nekonate</comment>
    <comment xml:lang="es">desconocido</comment>
    <comment xml:lang="eu">ezezaguna</comment>
    <comment xml:lang="fi">tuntematon</comment>
    <comment xml:lang="fo">ókent</comment>